### ISSUE TITLE
Enable push to S3 Staging bucket

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/devops-17#18]

**Comment by pdxdiver** [comment]
Need help?

**Comment by MikeTheCanuck** [comment]
Successful deploy:
https://travis-ci.org/hackoregon/team-budget-frontend/jobs/202516894

Unable to verify, as I don't have the ability to track down the HTTP endpoint or the URL for the deployed bucket.

**Comment by MikeTheCanuck** [comment]
Found the bucket's HTTP URL:
http://hacko-budget-staging.s3-website-us-west-2.amazonaws.com/
