### ISSUE TITLE
Enable Travis, S3 deploy for frontend

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/devops-17#22]
@Zak-Kent messaged me today with the following info/request:

> I received an message from Annie in the DevOps class and she let me know that she would be coming over tonight to help out. I wanted to give you a heads up incase she needed any additional information that you can think of.
> ...
> I also asked for her help in setting up our teams frontend repo. I saw the issue you opened where other teams had their repos setup already. I poked around in a few of them and have a better idea of what we need to setup. If you could point Annie or myself in the right direction of the
> 

The frontend repo to be linked to Travis and AWS S3 is here:
https://github.com/hackoregon/teamHomelessness-frontend

The DevOps procedure we're following for all frontend repos is documented here:
https://github.com/hackoregon/devops-17/blob/master/HOWTO%20Guides/HOWTO-Setup-TravisCI-to-push-front-end-code-to-AWS-S3.md

The staging bucket for Homelessness frontend is named "hacko-homelessness-staging".  The AWS keys for this bucket should be obtained from @pdxdiver (one of the devops folks may already have the keys from Dan).

# Background

Earlier this month, Zak shared the following as background (this is the snippet related to the frontend layer):

> I also only know of one way to set up the front end of a React project to make API calls and get around CORS issues. In a personal project I set up a simpl express proxy server to make the API calls but I'm not sure if this is the recommended method or the approach we're using at Hack Oregon.
> 
> If you have an ideas on the overall structure of setting up the AWS server and automating the process that would be awesome. I'd love to really learn how every piece of the DevOps stuff is working in order to make this setup happen. If you can point me in the right direction with any of this stuff, I can study up on the pieces we'll be using. Any help would be most appreciated

**Comment by PDXDiveChick** [comment]
This has been done.

**Comment by MikeTheCanuck** [comment]
Great news!

Could you please paste a link to the live Travis repo for this project?  When I browse to https://travis-ci.org/hackoregon/team-teamHomelessness-frontend, Travis reports "The repository at hackoregon/team-teamHomelessness-frontend was not found".

Also, I'm getting a "NoSuchBucket" error when I browse to http://hacko-homelessness-staging.s3-website-us-west-2.amazonaws.com.  Where is the team's bucket for frontend code?

**Comment by PDXDiveChick** [comment]
Homeless frontend links
https://travis-ci.org/hackoregon/teamHomelessness-frontend
http://hacko-homeless-staging.s3-website-us-west-2.amazonaws.com/

**Comment by PDXDiveChick** [comment]
Later today I will change the name from "homeless" to "homelessness" for consistency.

**Comment by MikeTheCanuck** [comment]
Super helpful, thank you!

I've added these links to the README for our devops squad:
https://github.com/hackoregon/devops-17/blob/master/README.md

**Comment by PDXDiveChick** [comment]
I've changed the staging link to be consistent with our naming: 
http://hacko-homelessness-staging.s3-website-us-west-2.amazonaws.com/

**Comment by MikeTheCanuck** [comment]
Awesome, thanks and we are officially done with this one!
