### ISSUE TITLE
Integrate backend server with TravisCI

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/devops-17#28]
We have a minimal API stack as of [this commit](https://github.com/hackoregon/team-budget/commit/570944ca10e07297be079f981102fb8d805a3dd7).

We now need to integrate with TravisCI, performing build (and whatever trivial test we can steal from another project - or Dan's assignments) and deploy.

We'll need an ECS destination and credentials to be able to make the deploy work.  Is this something we are allocating across the projects at this time?

**Comment by pdxdiver** [comment]
Working on test cluster w/workflow: ETA 2/27/

**Comment by MikeTheCanuck** [comment]
After discussions with @BrianHGrant and @terciero tonight, it appears that hands-free methods of deploying secrets (Django secret, database password, AWS creds) still end up ultimately depending on env vars configured in the CI system of choice.

With that in mind, the simplest approach seems best: add all secrets as environment variables in the Travis repo config, and let the build proceed that way.  Those secrets could eventually include:

- Container registry creds (e.g. AWS ECR authorization token)
- AWS user creds for landing container in AWS ECS (e.g. AWS_ACCESS_KEY_STAGING, AWS_SECRET_ACCESS_KEY_STAGING)
- DB app password (e.g. DB_PASSWORD_STAGING)
- Django secret (e.g. DJANGO_SECRET_STAGING)

The only challenge with this approach appears to be where to put the resulting container image.  If we can push it directly to our AWS environment, then that would work great.  If not, then we should investigate a private registry (which I'll file as a separate issue).

**Comment by MikeTheCanuck** [comment]
Background reading suggested by @terciero, for alternative approaches, includes:

- https://12factor.net/
- https://github.com/joke2k/django-environ
- https://www.vaultproject.io/
- http://docs.ansible.com/ansible/playbooks_vault.html

**Comment by MikeTheCanuck** [comment]
Tonight at Budget Team meeting, @meganmckissack confirmed that we are formally authorized to start spinning up a minimal ECS footprint in which to deploy the backend containers for all projects.

We'll need @pdxdiver's assistance to issue credentials that are authorized to manage an ECS instance in the Hack Oregon organization.

**Comment by pdxdiver** [comment]
This is done. See https://github.com/hackoregon/backend-service-pattern
