### ISSUE TITLE
Enable a minimal CI/CD pipeline for front-end developers (to the project's staging bucket)

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/devops-17#3]
**Goal:** get each Hack Oregon project's front-end team able to continuously deploy project files to their S3 staging bucket.

This work can proceed independently of issue #2, but the expectation is that many developers will be nervous about automated deploys until they have experienced the Hack Oregon front-end workflow themselves.

This work can proceed without completion of issue #1, but it will be quickly necessary to enable smoke tests so that broken commits don't expose a wide number of testers to bad "builds".

This work will require addressing:
- creation of AWS credentials that enable hands-free deployment from TravisCI to each project's S3 staging bucket
- how to prevent automatic file deployment when the smoke tests fail

**Comment by scottslewis** [comment]
+1

On Jan 29, 2017 1:26 PM, "Mike Lonergan" <notifications@github.com> wrote:

*Goal:* get each Hack Oregon project's front-end team able to continuously
deploy project files to their S3 staging bucket.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hackoregon/devops-17/issues/3>, or mute the thread

**Comment by MikeTheCanuck** [comment]
As of early last night (2017-02-14), the following projects have a frontend repo hooked to TravisCI and pushing to S3:
- Emergency Response https://github.com/hackoregon/emergency-response-frontend
- Housing https://github.com/hackoregon/housing-frontend

The following projects have the repo configured, but unclear if Travis & S3 are operational:
- Budget https://github.com/hackoregon/team-budget-frontend
- Transportation https://github.com/hackoregon/transportation-frontend

The Homelessness project frontend repo isn't yet started/visible.

**Comment by pdxdiver** [comment]
This is done
