### ISSUE TITLE
Initiate a strike team to integrate parameterized testing into Travis builds

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/devops-17#40]
There are three project teams whose backend repos have already committed a non-trivial amount of test code to `master`, and are presumably investing in this so that it can be integrated into Travis builds and prevent some broken builds from being deployed:

- Budget
- Housing
- Homelessness

The current (backend-service-pattern](https://github.com/hackoregon/backend-service-pattern) does not support automated testing via Travis.

I have personally invested an couple of weeks (see Issue #39) into trying to get Travis to successfully execute automated tests of the APIs as part of the build.

My current workaround is to hardcode all the env vars into the Travis config.  Is this workable for now?  Yes.  Is it scalable to multiple target environments from the same repo?  Not really, not without some ugly workarounds.

I'm concerned that the hard-coded Travis config is going to become a major pain in the next month.

I could use some serious help digging in and trying to figure out what I'm missing that continues to block my ability to make the "external file" approach succeed in Travis.

Can you folks help me?

**Comment by pdxdiver** [comment]
@MikeTheCanuck.  See the latest commit to the backend service pattern.  This issue is addressed.

**Comment by MikeTheCanuck** [comment]
I have zeroed in on a solution to this for the Budget backend over the past 24 hours, and validated it against the pattern that Dan has implemented in the backend-service-pattern.

See [Budget team PR 74](https://github.com/hackoregon/team-budget/pull/74/) for details.

I will work with the Housing and Homelessness teams if and when they need help integrating testing into their Travis build.
