### ISSUE TITLE
Enable Glacier on S3 buckets once versioning is turned on

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/devops-17#9]
Front-end development infrastructure will use S3 buckets as storage location for all static assets, including versioning of any data files.

To enable developers to know they're using current and known/good data that corresponds with current/known/good code, we will enable versioning in S3 buckets.

Once S3 bucket versioning is enabled, charges will climb as the volume of older-version data accumulates.  Since older versions of data will quickly become unused, we will enable migration of older versions of data to Glacier.  That way the data is ultimately available if needed, but will cost much less to store.

**Comment by pdxdiver** [comment]
Do we need to version the Front end bucket given, we could just redploy from git?  
Should we think about a strategy that let's us link commit to the bucket?  This assumes we are using scheme like semver.  I think bucket tagging could provides some useful features (ability to understand cost, linkage to git version etc)  

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTtagging.html

**Comment by pdxdiver** [comment]
Git takes care of this.  No need to got to glacier
